services:
  gestionvehicular.api:
    image: ${DOCKER_REGISTRY-}gestionvehicularapi
    build:
      context: .
      dockerfile: GestionVehicular.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__sql_connection=Server=db;Database=GestionVehicular;User Id=sa;Password=TuPassword123!;TrustServerCertificate=true;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_gestion
    environment:
      - SA_PASSWORD=TuPassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "TuPassword123!", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mssql_data: